name: Chocolatine-B_dop

run-name: ${{github.actor}} ${{github.event_name}}

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'


env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-REN-2-1-chocolatine-matthew.charuel.git
  EXECUTABLES: chocolatine


jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: coding-style
        run: ##check.sh $(pwd) $(pwd) ##commande du shell ??

  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: make
        timeout-minutes: 2
      - name: Clean
        run: make clean
      - name: check executables ##vérifier l'executable, échoue si absent ou non éxécutable
        run: ##if exec error alors exit
        ##${{ env.EXECUTABLES }}

  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: run tests
        run: ##tests criterion
        timeout-minutes: 2

  push_to_mirror:             ##push in repo mirror
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GITHUB_TOKEN }} ##pas la bonne phrase après secrets
