name: Chocolatine-B_dop

run-name: ${{github.actor}} ${{github.event_name}}

on:
  push:
    branches:
      ga-ignore-
  pull_request:
    branches:
      ga-ignore-


env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-REN-2-1-chocolatine-matthew.charuel.git
  EXECUTABLES: choco


jobs: ##check_compilation ; //run_tests ; // push
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            MIRROR_URL
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.GITHUB_TOKEN }}

  to_codecommit:                                        # <-- different jobs are executed in parallel.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            MIRROR_URL
          ssh_private_key:
            ${{ secrets.GITHUB_TOKEN }}