name: Chocolatine-B_dop

run-name: ${{github.actor}} ${{github.event_name}}

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-REN-2-1-chocolatine-matthew.charuel.git
  EXECUTABLES: chocolatine

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: coding-style
        run: check.sh $(pwd) $(pwd)

  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: make
        timeout-minutes: 2
      - name: Clean
        run: make clean
      - name: check executables
        run: |
          for i in ${{ env.EXECUTABLES }}
          do
            if [ ! -x "$i"]
              then
                echo "Error: $executable not found or not executable"
                exit 1
            fi
          done

  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: make
        timeout-minutes: 2
      - name: compilation run_tests
        run: make unit_tests
        timeout-minutes: 2

  push_to_mirror:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
