name: Chocolatine-B_dop

run-name: ${{github.actor}} ${{github.event_name}}

on:
  push:
    branches:
      ga-ignore-*
  pull_request:
    branches:
      ga-ignore-*


env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-REN-2-1-chocolatine-matthew.charuel.git
  EXECUTABLES: choco


jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    ##docker du coding style
    steps:
      - name: coding-style
        run: ##check.sh $(pwd) $(pwd) ##commande du shell ??
        ##if error exit

  check_program_compilation:
    runs-on: ubuntu-latest
    ##docker
    steps:
      - name: Build
        run: make
      ##timeout max 2min
      - name: Clean
        run: make clean
      - name: check executables ##vérifier l'executable, échoue si absent ou non éxécutable
        run: ##if exec error alors exit

  run_tests:
    runs-on: ubuntu-latest
    ##docker
    steps:
      - name: run tests
        run: ##tests criterion
      ##timeout max 2min

  push_to_mirror:             ##push in repo mirror
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            MIRROR_URL
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.GITHUB_TOKEN }}